# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c6e69795652c3b1aa76d141d2c9f79c1e88ebf534036128b23697668262e64a8867e98bf93bebf4cd3ea0867ed9cb867a6cf475a415366c99fa07682a8c6174

test:
  secret_key_base: a2560e19dd606ff52eb4a442d9be39b24af15fd8cc29bef7ca38680541db685c71e41a99d3630714508d8655a264ff6f18af813ad28580ab3456bd4843deadd7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
